(()=>{
const SPICES=['不辣','微微辣','微辣','小辣','中辣','大辣','大辣再辣'];
let orderOptions=null;
let records=JSON.parse(localStorage.getItem('posRecords')||'[]');
const saveRecords=()=>localStorage.setItem('posRecords',JSON.stringify(records));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const style=document.createElement('style');style.textContent=`
#historyBtn{background:#eee;color:#111;margin-right:7px}.order-meta{padding:10px 12px;background:#fff7d6;border-bottom:1px solid #eadb9e;font-size:14px;line-height:1.5;cursor:pointer}.fx-modal{padding:16px}.fx-modal h2{margin:0 0 12px}.fx-sec{margin:13px 0}.fx-title{font-weight:900;margin-bottom:7px}.fx-choices{display:flex;flex-wrap:wrap;gap:7px}.fx-choices label{display:flex;align-items:center;gap:5px;border:1px solid #ccc;border-radius:999px;padding:8px 10px;background:#fff}.fx-foot{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.fx-foot button,.record button{border:0;border-radius:9px;padding:8px 11px;font-weight:800}.fx-primary{background:#111;color:#fff}.fx-secondary{background:#eee}.fx-hidden{display:none!important}.stats{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:12px}.stat{background:#f2f2f2;border-radius:12px;padding:12px}.stat b{display:block;font-size:24px;margin-top:4px}.record{border:1px solid #ddd;border-radius:12px;padding:11px;margin:8px 0}.record-head{display:flex;justify-content:space-between;gap:8px;font-weight:900}.record-meta,.record-items{font-size:13px;color:#555;margin-top:5px}.record-actions{display:flex;gap:7px;margin-top:8px}.fx-input,.fx-select{width:100%;padding:10px;border:1px solid #bbb;border-radius:10px;font-size:16px}.fx-note{font-size:12px;color:#666;margin-top:8px}`;document.head.appendChild(style);

const header=document.querySelector('header');const editBtn=document.getElementById('editBtn');const historyBtn=document.createElement('button');historyBtn.id='historyBtn';historyBtn.textContent='紀錄/統計';header.insertBefore(historyBtn,editBtn);
const meta=document.createElement('div');meta.className='order-meta';meta.textContent='尚未設定內用/外帶與辣度';document.querySelector('.cart-head').insertAdjacentElement('afterend',meta);

function dlg(html){const d=document.createElement('dialog');d.innerHTML=`<div class="fx-modal">${html}</div>`;document.body.appendChild(d);return d}
const optDlg=dlg(`<h2>訂單選項</h2><div class="fx-sec"><div class="fx-title">用餐方式</div><div class="fx-choices"><label><input type="radio" name="fxService" value="內用">內用</label><label><input type="radio" name="fxService" value="外帶">外帶</label></div></div><div class="fx-sec"><div class="fx-title">辣度</div><div class="fx-choices" id="fxSpices"></div></div><div class="fx-sec fx-hidden" id="fxOil"><div class="fx-title">去油</div><div class="fx-choices"><label><input type="radio" name="fxOil" value="不去油" checked>不去油</label><label><input type="radio" name="fxOil" value="去油">去油</label></div></div><div id="fxTakeout" class="fx-hidden"><div class="fx-sec"><div class="fx-title">碗</div><div class="fx-choices"><label><input type="radio" name="fxBowl" value="要碗" checked>要碗</label><label><input type="radio" name="fxBowl" value="不要碗">不要碗</label></div></div><div class="fx-sec"><div class="fx-title">餐具</div><div class="fx-choices"><label><input type="radio" name="fxUtensils" value="要餐具" checked>要餐具</label><label><input type="radio" name="fxUtensils" value="不要餐具">不要餐具</label></div></div></div><div class="fx-foot"><button class="fx-secondary" id="fxOptCancel">取消</button><button class="fx-primary" id="fxOptSave">確認並結帳</button></div>`);
SPICES.forEach(s=>{const l=document.createElement('label');l.innerHTML=`<input type="radio" name="fxSpice" value="${s}">${s}`;optDlg.querySelector('#fxSpices').appendChild(l)});
const sel=n=>optDlg.querySelector(`input[name="${n}"]:checked`)?.value||'';
function syncOpt(){const service=sel('fxService'),spice=sel('fxSpice');optDlg.querySelector('#fxTakeout').classList.toggle('fx-hidden',service!=='外帶');optDlg.querySelector('#fxOil').classList.toggle('fx-hidden',SPICES.indexOf(spice)<3)}
optDlg.querySelectorAll('input[name="fxService"],input[name="fxSpice"]').forEach(e=>e.addEventListener('change',syncOpt));
function setRadio(name,value){if(!value)return;const e=optDlg.querySelector(`input[name="${name}"][value="${CSS.escape(value)}"]`);if(e)e.checked=true}
function openOptions(){optDlg.querySelectorAll('input[type=radio]').forEach(e=>e.checked=false);setRadio('fxOil','不去油');setRadio('fxBowl','要碗');setRadio('fxUtensils','要餐具');if(orderOptions){setRadio('fxService',orderOptions.service);setRadio('fxSpice',orderOptions.spice);setRadio('fxOil',orderOptions.oil);setRadio('fxBowl',orderOptions.bowl);setRadio('fxUtensils',orderOptions.utensils)}syncOpt();optDlg.showModal()}
meta.onclick=openOptions;optDlg.querySelector('#fxOptCancel').onclick=()=>optDlg.close();
function renderMeta(){if(!orderOptions){meta.textContent='尚未設定內用/外帶與辣度';return}const p=[orderOptions.service,orderOptions.spice];if(orderOptions.oil)p.push(orderOptions.oil);if(orderOptions.service==='外帶')p.push(orderOptions.bowl,orderOptions.utensils);meta.textContent=p.filter(Boolean).join('・')}
function cartText(){return Object.entries(cart).map(([i,q])=>`${items[i][1]}×${q}`).join('、')}
function completeCheckout(){if(!Object.keys(cart).length){alert('目前沒有商品');return}const t=total(),c=Number(cash.value||0);if(c&&c<t){alert('收款金額不足');return}const o=orderOptions;const rec={id:Date.now(),time:new Date().toISOString(),amount:t,service:o.service,spice:o.spice,oil:o.oil||'',bowl:o.bowl||'',utensils:o.utensils||'',items:cartText()};records.unshift(rec);saveRecords();alert(`結帳完成\n總計：$${t}${c?`\n收款：$${c}\n找零：$${c-t}`:''}`);cart={};cash.value='';orderOptions=null;renderCart();renderMeta()}
optDlg.querySelector('#fxOptSave').onclick=()=>{const service=sel('fxService'),spice=sel('fxSpice');if(!service||!spice){alert('請選擇內用/外帶與辣度');return}orderOptions={service,spice,oil:SPICES.indexOf(spice)>=3?sel('fxOil'):'',bowl:service==='外帶'?sel('fxBowl'):'',utensils:service==='外帶'?sel('fxUtensils'):''};renderMeta();optDlg.close();completeCheckout()};
document.getElementById('checkout').onclick=()=>{if(!Object.keys(cart).length){alert('目前沒有商品');return}if(!orderOptions){openOptions();return}completeCheckout()};
const oldClear=document.getElementById('clear').onclick;document.getElementById('clear').onclick=()=>{oldClear?.();orderOptions=null;renderMeta()};

const historyDlg=dlg(`<h2>結帳紀錄 / 統計</h2><div class="stats"><div class="stat">筆數<b id="fxCount">0</b></div><div class="stat">營業額<b id="fxRevenue">$0</b></div></div><div id="fxRecords"></div><div class="fx-note">紀錄只存在目前這台裝置的瀏覽器。若清除網站資料，紀錄也會消失。</div><div class="fx-foot"><button class="fx-primary" id="fxHistClose">關閉</button></div>`);
function localTime(s){return new Date(s).toLocaleString('zh-TW',{hour12:false})}
function renderHistory(){historyDlg.querySelector('#fxCount').textContent=records.length;historyDlg.querySelector('#fxRevenue').textContent='$'+records.reduce((s,r)=>s+Number(r.amount||0),0);const box=historyDlg.querySelector('#fxRecords');box.innerHTML=records.length?'':'<div style="text-align:center;color:#888;padding:25px">尚無結帳紀錄</div>';records.forEach(r=>{const d=document.createElement('div');d.className='record';d.innerHTML=`<div class="record-head"><span>#${String(r.id).slice(-5)}　${esc(r.service)}・${esc(r.spice)}</span><span>$${r.amount}</span></div><div class="record-meta">${localTime(r.time)}${r.oil?'・'+esc(r.oil):''}${r.bowl?'・'+esc(r.bowl):''}${r.utensils?'・'+esc(r.utensils):''}</div><div class="record-items">${esc(r.items)}</div><div class="record-actions"><button class="fx-secondary" data-edit>修改</button><button class="fx-secondary" data-del>刪除</button></div>`;d.querySelector('[data-edit]').onclick=()=>openEdit(r.id);d.querySelector('[data-del]').onclick=()=>{if(confirm('確定刪除這筆結帳紀錄？')){records=records.filter(x=>x.id!==r.id);saveRecords();renderHistory()}};box.appendChild(d)})}
historyBtn.onclick=()=>{renderHistory();historyDlg.showModal()};historyDlg.querySelector('#fxHistClose').onclick=()=>historyDlg.close();

let editId=null;const editDlg=dlg(`<h2>修改結帳紀錄</h2><div class="fx-sec"><div class="fx-title">金額</div><input id="fxEditAmount" class="fx-input" type="number" min="0"></div><div class="fx-sec"><div class="fx-title">用餐方式</div><select id="fxEditService" class="fx-select"><option>內用</option><option>外帶</option></select></div><div class="fx-sec"><div class="fx-title">辣度</div><select id="fxEditSpice" class="fx-select"></select></div><div class="fx-sec"><div class="fx-title">去油</div><select id="fxEditOil" class="fx-select"><option value="">不適用</option><option>不去油</option><option>去油</option></select></div><div class="fx-sec"><div class="fx-title">外帶碗</div><select id="fxEditBowl" class="fx-select"><option value="">不適用</option><option>要碗</option><option>不要碗</option></select></div><div class="fx-sec"><div class="fx-title">外帶餐具</div><select id="fxEditUtensils" class="fx-select"><option value="">不適用</option><option>要餐具</option><option>不要餐具</option></select></div><div class="fx-sec"><div class="fx-title">品項文字</div><input id="fxEditItems" class="fx-input" type="text"></div><div class="fx-foot"><button class="fx-secondary" id="fxEditCancel">取消</button><button class="fx-primary" id="fxEditSave">儲存修改</button></div>`);
SPICES.forEach(s=>editDlg.querySelector('#fxEditSpice').insertAdjacentHTML('beforeend',`<option>${s}</option>`));
function openEdit(id){const r=records.find(x=>x.id===id);if(!r)return;editId=id;editDlg.querySelector('#fxEditAmount').value=r.amount;editDlg.querySelector('#fxEditService').value=r.service;editDlg.querySelector('#fxEditSpice').value=r.spice;editDlg.querySelector('#fxEditOil').value=r.oil||'';editDlg.querySelector('#fxEditBowl').value=r.bowl||'';editDlg.querySelector('#fxEditUtensils').value=r.utensils||'';editDlg.querySelector('#fxEditItems').value=r.items||'';editDlg.showModal()}
editDlg.querySelector('#fxEditCancel').onclick=()=>editDlg.close();editDlg.querySelector('#fxEditSave').onclick=()=>{const r=records.find(x=>x.id===editId);if(!r)return;const a=Number(editDlg.querySelector('#fxEditAmount').value);if(!Number.isFinite(a)||a<0){alert('金額不正確');return}r.amount=a;r.service=editDlg.querySelector('#fxEditService').value;r.spice=editDlg.querySelector('#fxEditSpice').value;r.oil=editDlg.querySelector('#fxEditOil').value;r.bowl=editDlg.querySelector('#fxEditBowl').value;r.utensils=editDlg.querySelector('#fxEditUtensils').value;r.items=editDlg.querySelector('#fxEditItems').value.trim();saveRecords();editDlg.close();renderHistory()};
renderMeta();
})();